### ISSUE TITLE
Unsatisfied dependency expressed while implementing in Project

### ISSUE THREAD

**Issue by sebastianroming** [PredixDev/timeseries-bootstrap#5]
I want to create a new Spring Rest application and implement the timeseries-bootstrap.
I added it to pom.xml:

	<properties>
		[...]
		<predix-timeseries-client.version>2.1.2</predix-timeseries-client.version>
	</properties>

	<dependency>
		<groupId>com.ge.predix.solsvc</groupId>
		<artifactId>timeseries-bootstrap</artifactId>
		<version>${predix-timeseries-client.version}</version>
		<exclusions>
			<exclusion>
				<groupId>org.apache.geronimo.specs</groupId>
				<artifactId>geronimo-servlet_3.0_spec</artifactId>
			</exclusion>
			<exclusion>
				<groupId>javax.servlet</groupId>
				<artifactId>javax.servlet-api</artifactId>
			</exclusion>
		</exclusions>
	</dependency>

When running the application now locally, I get the following Error:

```
Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2016-11-07 15:17:49 ERROR [main]
                o.s.b.SpringApplication [SpringApplication.java:839] Application startup failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'timeseriesFactoryImpl': Unsatisfied dependency expressed through field 'tsIngestionWSConfig'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'timeseriesWSConfig': Unsatisfied dependency expressed through field 'wsMaxIdle'; nested exception is org.springframework.beans.TypeMismatchException: Failed to convert value of type [java.lang.String] to required type [int]; nested exception is java.lang.NumberFormatException: For input string: ""
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:569)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:349)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1219)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:751)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:861)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at de.swmachines.predix.boot.Application.main(Application.java:119)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'timeseriesWSConfig': Unsatisfied dependency expressed through field 'wsMaxIdle'; nested exception is org.springframework.beans.TypeMismatchException: Failed to convert value of type [java.lang.String] to required type [int]; nested exception is java.lang.NumberFormatException: For input string: ""
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:569)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:349)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1219)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:207)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1128)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1056)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:566)
	... 17 common frames omitted
Caused by: org.springframework.beans.TypeMismatchException: Failed to convert value of type [java.lang.String] to required type [int]; nested exception is java.lang.NumberFormatException: For input string: ""
	at org.springframework.beans.TypeConverterSupport.doConvert(TypeConverterSupport.java:77)
	at org.springframework.beans.TypeConverterSupport.convertIfNecessary(TypeConverterSupport.java:54)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1082)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1056)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:566)
	... 30 common frames omitted
Caused by: java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.valueOf(Unknown Source)
	at org.springframework.util.NumberUtils.parseNumber(NumberUtils.java:208)
	at org.springframework.beans.propertyeditors.CustomNumberEditor.setAsText(CustomNumberEditor.java:113)
	at org.springframework.beans.TypeConverterDelegate.doConvertTextValue(TypeConverterDelegate.java:468)
	at org.springframework.beans.TypeConverterDelegate.doConvertValue(TypeConverterDelegate.java:441)
	at org.springframework.beans.TypeConverterDelegate.convertIfNecessary(TypeConverterDelegate.java:199)
	at org.springframework.beans.TypeConverterDelegate.convertIfNecessary(TypeConverterDelegate.java:125)
	at org.springframework.beans.TypeConverterSupport.doConvert(TypeConverterSupport.java:61)
	... 34 common frames omitted

```

But I can't handle it - why this happens?

**Comment by katyatalluri** [comment]
Hello @sebastianroming,

In order to use the timeseries-bootstrap as a dependency, you will need to override the properties of timeseries-bootstrap in the calling app (aka. your new Spring Rest application). You will notice that timeseries-bootstrap requires a set of properties (https://github.com/PredixDev/timeseries-bootstrap/blob/master/config/application-template.properties). You will need to set those properties in the application.properties file in your Spring Rest application.

**Comment by sebastianroming** [comment]
Hi @katyatalluri 

thanks for your reply.

My /config/application.property already looks like this:

```
#properties for running locally or for unit tests
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.com.ge.predix.solsvc=DEBUG
logging.level.org.apache.http.impl.client=DEBUG
#<currentworkingdir>/config/application.properties are local ovverrides to src/main/resources(aka classpath)/application.properties
server.port=9092

spring.profiles.active=local

springfox.documentation.swagger.v2.path=/

predix.oauth.certLocation=
predix.oauth.tokenType=JWT
predix.oauth.resource=/oauth/token
predix.oauth.restPort=80
predix.oauth.proxyHost=
predix.oauth.proxyPort=
predix.oauth.grantType=client_credentials
predix.oauth.restHost=f0511eee-[...]-0c8cb0b2f6a9.predix-uaa.run.aws-usw02-pr.ice.predix.io
predix.oauth.clientIdEncode=true
predix.oauth.clientId=USER:SECRET
predix.timeseries.websocket.connection.retry=1
predix.timeseries.ingestUri=wss://gateway-predix-data-services.run.aws-usw02-pr.ice.predix.io/v1/stream/messages
predix.timeseries.baseUrl=https://time-series-store-predix.run.aws-usw02-pr.ice.predix.io
predix.timeseries.zoneid=[MY_ZONE_ID]
predix.timeseries.override.oauthOverride=false
predix.timeseries.override.oauthClientId=
predix.timeseries.override.oauthRestHost=
predix.websocket.pool.maxIdle=5
predix.websocket.pool.maxActive=5
predix.websocket.pool.maxWait=8000
predix.websocket.pool.maxInstances=5
```

So all of the required properties are set.

**Comment by katyatalluri** [comment]
Hello @sebastianroming,

From the stack trace it appears to be complaining about the setting of the property predix.websocket.pool.maxIdle which corresponds to the variable wsMaxIdle (line 51 of https://github.com/PredixDev/timeseries-bootstrap/blob/master/src/main/java/com/ge/predix/solsvc/timeseries/bootstrap/config/TimeseriesWSConfig.java). As I am not having the same issue, would you be able to debug to verify that the variable wsMaxIdle is being set?

**Comment by sebastianroming** [comment]
Hello @katyatalluri 

If I grab

**Comment by sebastianroming** [comment]
Hello @katyatalluri 

see this from Application.java:

    public static void main(String[] args)
    {
    	
    	TimeseriesWSConfig tsWSconfig = new TimeseriesWSConfig();
        System.out.println(tsWSconfig.getWsMaxIdle());
    	
        SpringApplication springApplication = new SpringApplication(Application.class);
        ApplicationContext ctx = springApplication.run(args);

        [....]

Output is 0, although predix.websocket.pool.madIdle is set to 5.

**Comment by sebastianroming** [comment]
@katyatalluri 

As I found out, it seems to refer to the @Controller annotation (org.springframework.stereotype.Controller).

**Comment by sebastianroming** [comment]
@katyatalluri 
I started - again - a project from scratch.

The application runs fine when I add the dependency to pom.xml.
But as soon as I add some of the required beans to my Controller, it crashes with the above error:

```
@Autowired
TimeseriesRestConfig timeseriesRestConfig;
@Autowired
protected TimeseriesFactory timeseriesFactory;
```

**Comment by katyatalluri** [comment]
Hello @sebastianroming,

While it is difficult to pinpoint the exact error though snippets of code, I would recommend you download this application: 
https://github.com/PredixDev/winddata-timeseries-service

The app windata-timeseries-service is a spring boot app that uses timeseries-bootstrap as a dependency jar to ingest and query timeseries data. You could compare/use the winddata-timeseries-service as a starter app. Please let me know if it helps resolve your issues.

**Comment by sebastianroming** [comment]
Hi @katyatalluri 

I already tried the winddata example. This works fine for me. 
But it uses JSR, which isn't useful to our application, so I tried to use the Spring Rest template as mentioned above.

**Comment by sebastianroming** [comment]
@katyatalluri This was not meant as reasolved. I just said The winddata example works but I can't use it for my application.
